export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const ADD_USER_PROFILE = 'ADD_USER_PROFILE';
export const ERROR_USER_PROFILE = 'ERROR_USER_PROFILE';
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const ADD_USER_POSTS = 'ADD_USER_POSTS';
export const ERROR_USER_POSTS = 'ERROR_USER_POSTS';
export const CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE';
